### ISSUE TITLE
Tests!

### ISSUE THREAD

**Issue by alcarney** [Moduleplanner/Moduleplanner.github.io#4]
Ideally we should be testing everything. 
- [x] For the html we can use `html-proofer` as with the code club website to check links etc.
  - [x]  Tests Added (Done by #11) 
  - [x]  Integrated with travis (Done by #15)
- [x] We should also test that the HTML generated by jekyll matches the structure expected by the javascript. (Done by #52)
  - Once in place if the structure changes this will cause tests to fail, prompting an update to the javascript rather than silently failing.
  - This can be done by writing custom tests that integrate with html proofer
- [x] We need something to validate the data (most important is to ensure that if module A requires B, then B also says it provides for A) 
  - [x]  `kwalify` - tests data format (Done by #23)
  - [x]  `custom code` - test if data makes sense (Done by #48)
  - [x]  Integrated with travis (Done by #23 and #48)
- [ ] Also the javascript should be tested. We might want to consider:
  - [ ] `Jasmine` - behavoiral based testing.
  - [ ] `JSVerify` - property based testing like QuickCheck and Hypothesis, integrates with Jasmine
  - [ ] `Karma` - Test runner for multiple browsers - and should give travis integration

**Comment by AdamPohl** [comment]
We should try and use Karma, it sounds better

**Comment by alcarney** [comment]
It sounds like karma is more of a runner than a tester - it can be used to
run Jasmine tests.

So maybe try getting Jasmine set up followed by karma to get Travis
integration?

**Comment by AdamPohl** [comment]
We will add tests for beta2
